const ATSKeywordsReducer = (previousState, action) => {
    return {
        ...previousState,
        ATSkeywords: [
            'Python',
            'JavaScript',
            'ES7',
            'ES6',
            'Webpack',
            'PHP',
            'Bootstrap',
            'Babel',
            'Gulp',
            'Sass',
            'Node',
            'NPM',
            'API',
            'REST',
            'npm',
            'React',
            'MySQL',
            'PHP',
            'Linux',
            'Ubuntu',
            'iptables',
            'Apache',
            'CLI',
            'Cloud',
            'JS',
            'ReactJS',
            'ESLint',
            'Karma',
            'Jasmine',
            'Protractor',
            'AngularJS',
            'Angular',
            'C',
            'C++',
            'WordPress',
            'Babel',
            'PHP',
            'React',
            'React.js',
            'Redux',
            'Higher Order Components',
            'React Context',
            'Express.js',
            'Redux'
        ]
    }
};

export {ATSKeywordsReducer};
